# Generated by Django 4.1.2 on 2022-10-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_alter_company_name_worker_waitingclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitingclient',
            name='service',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='service',
        ),
        migrations.RemoveField(
            model_name='company',
            name='adres',
        ),
        migrations.AddField(
            model_name='company',
            name='adress',
            field=models.CharField(default='---', help_text='<h4>Adress of company</h4>', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=80, verbose_name='company_name'),
        ),
        migrations.DeleteModel(
            name='CompletedTasks',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='WaitingClient',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
