# Generated by Django 4.1.2 on 2022-10-30 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_waitingclient_service_remove_worker_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='Company adress'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Company name'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Employee Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='main.company')),
            ],
        ),
    ]
